#!/usr/bin/env bats
# Tests for .github/actions/discord-release-notify inline shell logic.
#
# The shell logic lives inline in .github/actions/discord-release-notify/action.yml.
# The snippet below is a verbatim copy of the "Post release card to Discord"
# run block, so this test breaks if the action logic changes without updating
# the test.
#
# curl is stubbed on PATH so no network, docs site or Discord webhook is
# required. jq and date are the real binaries.
#
# Covers:
#   - empty webhook_url is a no-op success and posts nothing
#   - repo name maps to bot name, avatar URL and card slug (bluefin-lts)
#   - repo name maps to bot name, avatar URL and card slug (dakota)
#   - unknown repo names fall back to the Bluefin mascot
#   - suffix matching is anchored on the owner separator
#   - the card is downloaded from the slug-specific docs URL
#   - a YYYYMMDD tag suffix renders a pretty thread title
#   - an unparseable tag falls back to the raw tag in the thread title
#   - payload_json carries username, avatar_url, thread_name and empty mentions
#   - the card file is attached as image/png and the webhook URL is the target
#   - a failed card download fails the step before anything is posted
#   - a non-200 webhook response fails the step with the status on stderr
#   - a 200 webhook response succeeds

setup() {
  TEST_TMP=$(mktemp -d)
  export TEST_TMP

  export STUB_BIN="${TEST_TMP}/bin"
  mkdir -p "$STUB_BIN"
  export CURL_LOG="${TEST_TMP}/curl.log"
  export PAYLOAD_FILE="${TEST_TMP}/payload.json"
  : >"$CURL_LOG"

  cat >"${STUB_BIN}/curl" <<'STUB'
#!/usr/bin/env bash
# Distinguish the card download (-o FILE) from the webhook post (-F ...).
out=""
is_post=0
prev=""
for arg in "$@"; do
  [[ "$prev" == "-o" ]] && out="$arg"
  case "$arg" in
    -F) is_post=1 ;;
    payload_json=*) printf '%s' "${arg#payload_json=}" >"$PAYLOAD_FILE" ;;
  esac
  prev="$arg"
done

if (( is_post )); then
  # payload_json is multi-line; flatten so the log stays one line per call.
  printf 'POST %s\n' "$(printf '%s' "$*" | tr '\n' ' ')" >>"$CURL_LOG"
  printf 'body\n%s\n' "${CURL_HTTP_STATUS:-200}"
  exit "${CURL_POST_EXIT:-0}"
fi

echo "GET $*" >>"$CURL_LOG"
if [[ "${CURL_DOWNLOAD_EXIT:-0}" != "0" ]]; then
  exit "${CURL_DOWNLOAD_EXIT}"
fi
[[ -n "$out" ]] && printf 'fake-png' >"$out"
exit 0
STUB
  chmod +x "${STUB_BIN}/curl"

  SNIPPET="${TEST_TMP}/notify.sh"
  export SNIPPET
  cat >"$SNIPPET" <<'SNIPPET_EOF'
[ -n "$WEBHOOK_URL" ] || { echo "No Discord webhook URL configured, skipping."; exit 0; }

repo_short="${REPO##*/}"

card_file="/tmp/release-card-dark.png"

# Derive mascot avatar + display name from repo name
# Mapping mirrors generate-card-images.mjs in projectbluefin/documentation
DOCS_RAW="https://raw.githubusercontent.com/projectbluefin/documentation/main/static/img"
case "${REPO}" in
  */bluefin-lts) bot_name="Bluefin LTS"; avatar_url="${DOCS_RAW}/bluefin-lts-release-bot.svg"; card_slug="bluefin-lts" ;;
  */dakota)      bot_name="Dakota";       avatar_url="${DOCS_RAW}/characters/dakotaraptor.png"; card_slug="dakota" ;;
  *)             bot_name="Bluefin";      avatar_url="${DOCS_RAW}/bluefin-release-bot.png";     card_slug="bluefin" ;;
esac

# Pretty date from tag — stable-20260623 → "June 23, 2026"
date_raw="${TAG_NAME##*-}"
pretty_date=$(date -d "${date_raw:0:4}-${date_raw:4:2}-${date_raw:6:2}" "+%B %-d, %Y" 2>/dev/null || echo "$TAG_NAME")
post_title="${bot_name} — ${pretty_date}"

# Fetch the rich release card from the docs site — always reflects current release,
# includes kernel version, package counts, and raptor mascot artwork.
# Generated by projectbluefin/documentation scripts/generate-card-images.mjs
card_file="/tmp/release-card-dark.png"
curl -sfL "https://docs.projectbluefin.io/img/cards/${card_slug}-dark.png" -o "${card_file}"

# Post PNG as plain file attachment — Discord renders it full-width, no embed shrinkage
payload=$(jq -n \
  --arg thread_name "$post_title" \
  --arg bot_name "$bot_name" \
  --arg avatar_url "$avatar_url" \
  '{
    "username": $bot_name,
    "avatar_url": $avatar_url,
    "thread_name": $thread_name,
    "allowed_mentions": {"parse": []}
  }')

response=$(curl -sf -w "\n%{http_code}" \
  -H "User-Agent: DiscordBot (https://github.com/projectbluefin/common, 1.0)" \
  -F "payload_json=${payload}" \
  -F "files[0]=@${card_file};type=image/png" \
  "${WEBHOOK_URL}")

http_status=$(tail -1 <<< "$response")

[[ "$http_status" == "200" ]] || {
  echo "Discord post failed: HTTP $http_status" >&2
  exit 1
}
SNIPPET_EOF
}

teardown() {
  rm -rf "$TEST_TMP"
}

# Run the action step the way GitHub runs `shell: bash` composite steps.
run_notify() {
  export WEBHOOK_URL="${WEBHOOK_URL-https://discord.example/api/webhooks/1/abc}"
  export TAG_NAME="${TAG_NAME-stable-20260623}"
  export REPO="${REPO-projectbluefin/bluefin}"
  PATH="${STUB_BIN}:${PATH}" run bash -e "$SNIPPET"
}

payload_field() {
  jq -r "$1" <"$PAYLOAD_FILE"
}

@test "empty webhook url is a no-op success" {
  WEBHOOK_URL="" run_notify
  [ "$status" -eq 0 ]
  [[ "$output" == *"No Discord webhook URL configured, skipping."* ]]
  [ ! -s "$CURL_LOG" ]
}

@test "bluefin-lts repo maps to the LTS bot name, avatar and card slug" {
  REPO="projectbluefin/bluefin-lts" run_notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .username)" = "Bluefin LTS" ]
  [ "$(payload_field .avatar_url)" = "https://raw.githubusercontent.com/projectbluefin/documentation/main/static/img/bluefin-lts-release-bot.svg" ]
  grep -q "img/cards/bluefin-lts-dark.png" "$CURL_LOG"
}

@test "dakota repo maps to the Dakota bot name, avatar and card slug" {
  REPO="projectbluefin/dakota" run_notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .username)" = "Dakota" ]
  [ "$(payload_field .avatar_url)" = "https://raw.githubusercontent.com/projectbluefin/documentation/main/static/img/characters/dakotaraptor.png" ]
  grep -q "img/cards/dakota-dark.png" "$CURL_LOG"
}

@test "unknown repo falls back to the Bluefin mascot and slug" {
  REPO="projectbluefin/common" run_notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .username)" = "Bluefin" ]
  [ "$(payload_field .avatar_url)" = "https://raw.githubusercontent.com/projectbluefin/documentation/main/static/img/bluefin-release-bot.png" ]
  grep -q "img/cards/bluefin-dark.png" "$CURL_LOG"
}

@test "repo suffix match is anchored on the owner separator" {
  REPO="projectbluefin/not-bluefin-lts" run_notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .username)" = "Bluefin" ]
  grep -q "img/cards/bluefin-dark.png" "$CURL_LOG"
}

@test "card is downloaded before the webhook post" {
  run_notify
  [ "$status" -eq 0 ]
  [ "$(head -1 "$CURL_LOG" | cut -d' ' -f1)" = "GET" ]
  [ "$(tail -1 "$CURL_LOG" | cut -d' ' -f1)" = "POST" ]
}

@test "YYYYMMDD tag suffix renders a pretty thread title" {
  TAG_NAME="stable-20260623" run_notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .thread_name)" = "Bluefin — June 23, 2026" ]
}

@test "unparseable tag falls back to the raw tag in the thread title" {
  TAG_NAME="v1.2.3" run_notify
  [ "$status" -eq 0 ]
  [ "$(payload_field .thread_name)" = "Bluefin — v1.2.3" ]
}

@test "payload suppresses all mentions" {
  run_notify
  [ "$status" -eq 0 ]
  [ "$(jq -c '.allowed_mentions.parse' <"$PAYLOAD_FILE")" = "[]" ]
}

@test "card file is attached as image/png and posted to the webhook url" {
  WEBHOOK_URL="https://discord.example/api/webhooks/42/token" run_notify
  [ "$status" -eq 0 ]
  post=$(grep '^POST ' "$CURL_LOG")
  [[ "$post" == *"files[0]=@/tmp/release-card-dark.png;type=image/png"* ]]
  [[ "$post" == *"https://discord.example/api/webhooks/42/token"* ]]
}

@test "failed card download fails the step before posting" {
  CURL_DOWNLOAD_EXIT=22 run_notify
  [ "$status" -ne 0 ]
  ! grep -q '^POST ' "$CURL_LOG"
}

@test "non-200 webhook response fails the step and reports the status" {
  CURL_HTTP_STATUS=429 run_notify
  [ "$status" -eq 1 ]
  [[ "$output" == *"Discord post failed: HTTP 429"* ]]
}

@test "200 webhook response succeeds" {
  CURL_HTTP_STATUS=200 run_notify
  [ "$status" -eq 0 ]
}
